# Setup
title: Lanyon
tagline: "A Jekyll theme"
description: ""
url: https://yoonlang.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: 최윤석
  url: https://yoonlang.github.io
  email: cdt9473@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
